- name: Set up macOS machine
  connection: local
  hosts: localhost
  vars_files:
    - homebrew.yml
    - vault.yml

  vars:
    fish_update_completions: false

  roles:
    - role: geerlingguy.mac.homebrew
      tags:
        - brew

  tasks:
    - import_tasks: tasks/osx_defaults.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/fish.yml
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/starship.yml
    - import_tasks: tasks/kitty.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/asdf.yml
    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/zed.yml
