---
- name: create config dir
  file:
    path: ~/.config/fish
    state: directory
    mode: 0755

- name: link fish config
  file:
    src: "{{ playbook_dir }}/files/fish/config.fish"
    dest: ~/.config/fish/config.fish
    mode: 0644
    state: link
    force: true

- name: link fish functions
  copy:
    src: files/fish/functions/
    dest: ~/.config/fish/functions/
    mode: 0644
    state: link
    force: true

- name: add fish to shells
  lineinfile:
    path: /etc/shells
    line: /opt/homebrew/opt/fish
    state: present
  become: true

- name: register current ansible user id
  set_fact:
    current_user_id: "{{ ansible_user_id }}"

- name: change default shell to fish
  user:
    name: "{{ current_user_id }}"
    shell: /opt/homebrew//bin/fish
  become: true

- name: update completions
  shell: "fish_update_completions"
  args:
    executable: "{{ ansible_user_shell }}"
  when: fish_update_completions
