---
- name: link git config
  file:
    src: "{{ playbook_dir }}/files/{{ item }}"
    dest: ~/.{{ item}}
    mode: 0644
    state: link
    force: true
  loop:
    - gitconfig
    - gitconfig-imen
    - gitconfig-personal

- name: link gitignore
  file:
    src: "{{ playbook_dir }}/files/gitignore"
    dest: ~/.gitignore
    mode: 0644
    state: link
    force: true

- name: add lfs plugin to git
  shell: "git lfs install"
  args:
    executable: "{{ ansible_user_shell }}"
  changed_when: false
