---
- name: create tmux config
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/tmux"
    dest: ~/.config/tmux
    mode: 0744
    state: link
    force: true

- name: create plugin directory
  ansible.builtin.file:
    path: ~/.config/tmux/plugins
    state: directory
    recurse: true
    mode: 0744

- name: clone tpm repo
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.config/tmux/plugins/tpm
    update: true
    single_branch: true
    version: master
