- name: add convenience function
  ansible.builtin.copy:
    dest: ~/.config/fish/functions/ya.fish
    content: |
      function ya
        set tmp (mktemp -t "yazi-cwd.XXXXX")
        yazi $argv --cwd-file="$tmp"
        if set cwd (cat -- "$tmp"); and [ -n "$cwd" ]; and [ "$cwd" != "$PWD" ]
          cd -- "$cwd"
        end
        rm -f -- "$tmp"
      end

- name: add yazi config dir
  ansible.builtin.file:
    path: ~/.config/yazi/
    state: directory

- name: add yazi plugin dir
  ansible.builtin.file:
    path: ~/.config/yazi/plugins/smart-enter.yazi
    state: directory
    recurse: true

- name: add smart enter plugin
  ansible.builtin.copy:
    dest: ~/.config/yazi/plugins/smart-enter.yazi/init.lua
    content: |
      return {
        entry = function()
          local h = cx.active.current.hovered
          ya.manager_emit(h and h.cha.is_dir and "enter" or "open", {})
        end,
      }

- name: add smart-enter plugin to keymap
  ansible.builtin.blockinfile:
    path: ~/.config/yazi/keymap.toml
    append_newline: true
    prepend_newline: true
    create: true
    block: |
      [[manager.prepend_keymap]]
        on   = [ "l" ]
        run = "plugin --sync smart-enter"
        desc = "Enter the child directory, or open the file"
