require('kschweikert.plugins-setup')
require('kschweikert.core.options')
require('kschweikert.core.keymaps')
require('kschweikert.core.colorscheme')

require('kschweikert.plugins.lualine')
require('kschweikert.plugins.lsp-zero')
require('kschweikert.plugins.telescope')
require('kschweikert.plugins.nvim-tree')
require("kschweikert.plugins.treesiter")
require("kschweikert.plugins.notify")
