return {
  cmd = { "emmet-language-server", "--stdio" },
  root_markers = { ".git" },
  filetypes = {
    "astro",
    "css",
    "eelixir",
    "elixir",
    "eruby",
    "gleam",
    "heex",
    "html",
    "htmldjango",
    "javascriptreact",
    "less",
    "pug",
    "sass",
    "scss",
    "svelte",
    "typescriptreact",
    "vue",
  },
}
