# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 2000

[username]
show_always = true
format = "[$user]($style)"

[hostname]
ssh_only = false
format = "[@$hostname]($style) "

[status]
disabled = false
