# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 2000
scan_timeout = 10

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold green)"

[username]
show_always = true
format = "[$user]($style)"

[hostname]
ssh_only = false
format = "[@$hostname]($style) "

[status]
disabled = false
format = "[$status]($style)"
symbol = "[x](bold red) "

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[bun]
symbol = "bun "

[c]
symbol = "C "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[directory]
read_only = " ro"

[docker_context]
symbol = "docker "
disabled = true

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[git_branch]
symbol = ""

[golang]
symbol = "go "

[julia]
symbol = "jl "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[nim]
symbol = "nim "

[os]
disabled = true

[package]
symbol = "pkg "
disabled = true

[php]
symbol = "php "

[python]
symbol = "py "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "

[terraform]
symbol = "terraform "

[zig]
symbol = "zig "
